import type { ExerciseDefinition } from './types'

export const OLD_GYM_EXERCISES: ExerciseDefinition[] = [
  { id:'old_hammer_shoulder_press', name:'Жим плеч в Hammer', category:'ПЛЕЧИ', muscleGroup:'Плечи', movementPattern:'Вертикальный жим', equipment:'Hammer', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'30 кг ×15', lastKnown:'50 кг ×12', bestKnown:'70 кг ×12', historyNote:'Лучший подтверждённый результат 70×12.' },
  { id:'old_db_lateral_raise_standing', name:'Махи гантелями в стороны стоя', category:'ПЛЕЧИ', muscleGroup:'Плечи', movementPattern:'Отведение плеча', equipment:'Гантели', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'7,5 кг ×20', lastKnown:'10 кг ×15', bestKnown:'15 кг ×12', historyNote:'Без читинга; 15×10 встречалось до технического отказа.' },
  { id:'old_reverse_pec_deck', name:'Обратная бабочка', category:'ПЛЕЧИ / ЗАДНЯЯ ДЕЛЬТА', muscleGroup:'Задняя дельта', movementPattern:'Задняя дельта', equipment:'Тренажёр', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'31 кг ×12', lastKnown:'40 кг ×12', bestKnown:'49 кг ×12' },
  { id:'old_hammer_chest_press', name:'Жим в Hammer / Chest Press', category:'ГРУДЬ', muscleGroup:'Грудь', movementPattern:'Горизонтальный жим', equipment:'Hammer', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'50 кг ×15', lastKnown:'75 кг ×12', bestKnown:'85 кг ×7', historyNote:'Также выполнялось 80×8.' },
  { id:'old_incline_db_press', name:'Жим гантелей на наклонной скамье', category:'ГРУДЬ', muscleGroup:'Грудь', movementPattern:'Наклонный жим', equipment:'Гантели', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'25 кг ×5', lastKnown:'27,5 кг ×9', bestKnown:'27,5 кг ×11', historyNote:'Первые повторы из мёртвой точки часто были самыми тяжёлыми.' },
  { id:'old_dips', name:'Брусья с собственным весом', category:'ГРУДЬ', muscleGroup:'Грудь', movementPattern:'Жим собственным весом', equipment:'Брусья', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'BW ×11–12', lastKnown:'BW ×12', bestKnown:'BW ×13', historyNote:'Наклон корпуса вперёд; последний сет доходил до отказа.' },
  { id:'old_pec_deck', name:'Pec Deck', category:'ГРУДЬ', muscleGroup:'Грудь', movementPattern:'Горизонтальное приведение', equipment:'Тренажёр', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'40 кг ×15', lastKnown:'50 кг ×10', bestKnown:'50 кг ×12' },
  { id:'old_lat_pulldown', name:'Тяга верхнего блока к груди', category:'СПИНА', muscleGroup:'Спина', movementPattern:'Вертикальная тяга', equipment:'Блок', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'68 кг ×15', lastKnown:'122 кг ×10', bestKnown:'131 кг ×9', historyNote:'Чёрная рукоять; рывковые повторы не считать.' },
  { id:'old_seated_row', name:'Горизонтальная тяга', category:'СПИНА', muscleGroup:'Спина', movementPattern:'Горизонтальная тяга', equipment:'Тренажёр', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'49,9 кг ×12', lastKnown:'59 кг ×10', bestKnown:'68 кг ×8', historyNote:'На 68 кг техника ухудшалась после 8 повторов.' },
  { id:'old_db_pullover', name:'Пуловер с гантелью', category:'СПИНА', muscleGroup:'Спина', movementPattern:'Разгибание плеча', equipment:'Гантель', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'25 кг ×12', lastKnown:'27,5 кг ×15', bestKnown:'35 кг ×10' },
  { id:'old_db_shrug', name:'Шраги с гантелями', category:'ТРАПЕЦИИ', muscleGroup:'Трапеции', movementPattern:'Элевация лопатки', equipment:'Гантели', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'37,5 кг ×12', lastKnown:'40 кг ×13', bestKnown:'42,5 кг ×12', historyNote:'Пауза около 1 сек в верхней точке.' },
  { id:'old_leg_press', name:'Жим ногами', category:'НОГИ', muscleGroup:'Ноги', movementPattern:'Жим ногами', equipment:'Тренажёр', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'120 кг ×15', lastKnown:'190 кг ×10', bestKnown:'200 кг ×8', historyNote:'Полная амплитуда; 200×8 без запаса.' },
  { id:'old_leg_extension', name:'Разгибание ног', category:'НОГИ / КВАДРИЦЕПС', muscleGroup:'Квадрицепс', movementPattern:'Разгибание колена', equipment:'Тренажёр', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'95,3 кг ×15', lastKnown:'104,3 кг ×12', bestKnown:'104,3 кг ×12', historyNote:'Дроп-сет 104,3→77,1→49,9 по 10 повторений.' },
  { id:'old_leg_curl', name:'Сгибание ног', category:'НОГИ / БИЦЕПС БЕДРА', muscleGroup:'Бицепс бедра', movementPattern:'Сгибание колена', equipment:'Тренажёр', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'50 кг ×15', lastKnown:'60 кг ×10', bestKnown:'69 кг ×12', historyNote:'69 кг было на другом сидячем тренажёре — напрямую не сравнивать.' },
  { id:'old_straight_bar_curl', name:'Подъём прямой штанги на бицепс', category:'БИЦЕПС', muscleGroup:'Бицепс', movementPattern:'Сгибание локтя', equipment:'Штанга', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'гриф +7,5 кг/сторона ×12', lastKnown:'гриф +10 кг/сторона ×10', bestKnown:'гриф +15 кг/сторона ×6' },
  { id:'old_ez_curl', name:'Сгибание EZ-штанги', category:'БИЦЕПС', muscleGroup:'Бицепс', movementPattern:'Сгибание локтя', equipment:'EZ-штанга', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'гриф +10 кг/сторона ×12', lastKnown:'гриф +15 кг/сторона ×6', bestKnown:'гриф +15 кг/сторона ×8' },
  { id:'old_hammer_curl', name:'Молотки стоя', category:'БИЦЕПС / БРАХИАЛИС', muscleGroup:'Бицепс', movementPattern:'Сгибание локтя', equipment:'Гантели', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'10 кг ×12', lastKnown:'12,5 кг ×12', bestKnown:'15 кг ×6', historyNote:'Синхронно или попеременно.' },
  { id:'old_db_skullcrusher', name:'Французский жим лёжа с гантелями', category:'ТРИЦЕПС', muscleGroup:'Трицепс', movementPattern:'Разгибание локтя', equipment:'Гантели', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'12,5 кг ×12', lastKnown:'12,5 кг ×10', bestKnown:'15 кг ×10' },
  { id:'old_cable_pushdown', name:'Разгибание рук на верхнем блоке', category:'ТРИЦЕПС', muscleGroup:'Трицепс', movementPattern:'Разгибание локтя', equipment:'Кроссовер', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'40 кг ×15', lastKnown:'59 кг ×12', bestKnown:'77 кг ×10', historyNote:'Использовались разные рукояти и, вероятно, разные блоки.' },
  { id:'old_overhead_cable_extension', name:'Разгибание рук над головой на блоке', category:'ТРИЦЕПС', muscleGroup:'Трицепс', movementPattern:'Разгибание локтя', equipment:'Кроссовер', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'40 кг ×15', lastKnown:'49,9 кг ×12', bestKnown:'59 кг ×13' },
  { id:'old_reverse_ez_curl', name:'Обратные сгибания EZ-штанги', category:'ПРЕДПЛЕЧЬЯ / БРАХИАЛИС', muscleGroup:'Предплечья', movementPattern:'Сгибание локтя', equipment:'EZ-штанга', weightUnit:'kg', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'гриф +10 кг ×12', lastKnown:'гриф +10 кг ×12', bestKnown:'гриф +10 кг ×12' },
  { id:'old_close_grip_pushup', name:'Узкие отжимания', category:'ТРИЦЕПС', muscleGroup:'Трицепс', movementPattern:'Жим собственным весом', equipment:'Собственный вес', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'BW ×12', lastKnown:'BW ×12', bestKnown:'BW ×12' },
  { id:'old_bench_dips', name:'Обратные отжимания от скамьи', category:'ТРИЦЕПС', muscleGroup:'Трицепс', movementPattern:'Жим собственным весом', equipment:'Скамья', gym:'Старый зал', known:true, suitability:'known', warmupKnown:'BW ×20', lastKnown:'BW ×20', bestKnown:'BW ×20', historyNote:'Ноги вытянуты; глубокая амплитуда.' }
]
