import type { ExerciseDefinition } from './types'

export const REHAB_AND_AUX_EXERCISES: ExerciseDefinition[] = [
  { id:'wall_pushup', name:'Wall Push-up', category:'ПЛЕЧО / REHAB', muscleGroup:'Грудь', movementPattern:'Жим собственным весом', equipment:'Стена', rehab:true, gym:'Новый зал', known:true, suitability:'known', defaultSets:1, defaultReps:'15', lastKnown:'BW ×15', rehabStatus:'🟢', lastPain:'1/10', lastRehabDate:'2026-08-30', historyNote:'Ранний тест перед возвратом Chest Press.' },
  { id:'cable_er_elbow_tucked', name:'Cable ER · локоть прижат', category:'ПЛЕЧО / REHAB', muscleGroup:'Плечи', movementPattern:'Наружная ротация', equipment:'Кроссовер', weightUnit:'kg', perSide:'arm', rehab:true, gym:'Новый зал', known:true, suitability:'known', defaultSets:2, defaultReps:'10', lastKnown:'2,3 кг ×10×2', bestKnown:'6,8 кг ×10', rehabStatus:'🟢', historyNote:'Ранняя стадия динамической наружной ротации; затем прогрессия ушла в углы 30–90°.' },
  { id:'cable_er_30_45', name:'Cable ER @30–45°', category:'ПЛЕЧО / REHAB', muscleGroup:'Плечи', movementPattern:'Наружная ротация', equipment:'Кроссовер', weightUnit:'kg', perSide:'arm', rehab:true, gym:'Новый зал', known:true, suitability:'known', defaultSets:2, defaultReps:'10', lastKnown:'6,8 кг ×10', rehabStatus:'🟢', lastPain:'0/10', historyNote:'13.09 новая более открытая позиция переносилась полностью безболезненно.' },
  { id:'reverse_pec_deck', name:'Reverse Pec Deck', category:'ПЛЕЧИ / ЗАДНЯЯ ДЕЛЬТА', muscleGroup:'Задняя дельта', movementPattern:'Задняя дельта', equipment:'Тренажёр', weightUnit:'kg', gym:'Новый зал', known:true, suitability:'known', defaultSets:2, defaultReps:'10–15', lastKnown:'45 кг ×10; 45 кг ×15', bestKnown:'45 кг ×15', rehabStatus:'🟢', lastPain:'≈1–2/10', lastRehabDate:'2026-09-22', historyNote:'Возврат из отведения переносился без нарастания симптома.' },
  { id:'wide_grip_pullup', name:'Подтягивания широким хватом', category:'СПИНА', muscleGroup:'Спина', movementPattern:'Вертикальная тяга', equipment:'Турник', gym:'Новый зал', known:true, suitability:'known', defaultSets:2, defaultReps:'5–10', lastKnown:'BW ×5+6+5', rehabStatus:'🟢', lastPain:'0/10', historyNote:'На 11.09 плечо в движении не ощущалось.' },
  { id:'db_lateral_raise', name:'Махи гантелями в стороны', category:'ПЛЕЧИ', muscleGroup:'Плечи', movementPattern:'Отведение плеча', equipment:'Гантели', weightUnit:'kg', gym:'Новый зал', known:true, suitability:'known', defaultSets:2, defaultReps:'12–15', lastKnown:'9 кг ×12 (rehab-тест)', rehabStatus:'🟢', lastPain:'1,5–2/10 на раннем этапе', historyNote:'Использовалось как тест при возвращении отведения; позже одно-ручный cable lateral переносился 0/10.' },
  { id:'hip_adductor', name:'Hip Adductor', category:'НОГИ / ПРИВОДЯЩИЕ', muscleGroup:'Приводящие', movementPattern:'Приведение бедра', equipment:'Тренажёр', weightUnit:'kg', gym:'Новый зал', known:true, suitability:'known', defaultSets:2, defaultReps:'12–18', lastKnown:'45 кг ×15×2', bestKnown:'45 кг ×15×2' }
]
